swagger: "2.0"
info:
  description: "This is the MoE api documentation. Here you find all APIs related to the system."
  version: "1.0.0"
  title: "MoE API Doc"
  contact:
    email: "nizarm@opensource.lk"
basePath: "/v2"
schemes:
  - "https"

paths:
  /student/{sid}:
    get:
      summary: "Find student by ID"
      description: "Returns a single student"
      operationId: "getStudentById"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "sid"
          in: "path"
          description: "ID of student to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Student"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Student not found"

definitions:
  Student:
    type: "object"
    properties:
      name:
        type: "string"
        example: "kamani"
      school_name:
        type: "string"
        example: "vishaka vidyalaya"
      zone:
        type: "string"
        example: "central"
      email:
        type: "string"
        example: "kamani@gmail.com"
      province:
        type: "string"
        example: "central"
      sis_number:
        type: "string"
        example: "XXXX-XXXX-XXXX"

  Institute:
    type: "object"
    properties:
      name:
        type: "string"
        example: "ALUDENIYA M.V"
      code:
        type: "string"
        example: "03002"
      address:
        type: "string"
        example: "ALUDENIYA, KANDY"
      telephone:
        type: "string"
        example: "0811234561"
      date_opened:
        type: "string"
        example: "1934-01-01"
      date_closed:
        type: "string"
        example: "null"
      year_opened:
        type: "string"
        example: "1934-01-01"
      year_closed:
        type: "string"
        example: "1934-01-01"